//
export const TYPE = [
  "Affidavit",
  "Age Declaration",
  "Audio",
  "Award",
  "Birth Certificate",
  "Certificate",
  "Certificate of Occupancy (C of O)",
  "CV/R&eacute;sum&eacute;",
  "Document",
  "Driver&apos;s License",
  "Hospital Card (HMO)",
  "ID Card",
  "Image",
  "Int&apos;l Passport",
  "Marriage Certificate",
  "Medical Report",
  "National ID Card",
  "Particulars",
  "Photograph",
  "Receipt/Teller",
  "Resident Permit",
  "Staff ID Card",
  "Statement",
  "Student ID Card",
  "Utility Bill",
  "Video",
  "Voter&apos;s Card",
  "Work Permit",
];
